# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

import os
import sys
#sys.path.insert(0, os.path.abspath('../..'))
sys.path.insert(0, os.path.abspath('../..'))

# -- Project information -----------------------------------------------------

project = 'ANEMO'
copyright = '2023, chloe pasturel'
author = 'Chloe Pasturel'

# The short X.Y version
version = '2.0.0'
# The full version, including alpha/beta/rc tags
release = '2.0.0'


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
    'nbsphinx',
    'sphinx_copybutton',
    #'numpydoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.autosectionlabel',
]

html_css_files = ['_static/custom.css',]


napoleon_use_param=False
napoleon_use_rtype=False

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = ['.rst']

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', '**.ipynb_checkpoints']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'trac'


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
html_theme_options = {
    'show_powered_by': False,
    'github_user': 'invibe',
    'github_repo': 'ANEMO',
    'github_banner': False,
    'github_button': True,
    'github_type': 'watch',
    'github_count': False,
    'show_relbars': True,

    'fixed_sidebar': True,
    'sidebar_width': '300px',
    'page_width': 'auto',
    'font_family': 'Open Sans',
    'link_hover': '#FF0000',
    'link': '#640000',
    'code_text': '#850000',
    'code_bg': 'transparent',
    'sidebar_header': '#4D4D4D',
    'sidebar_link': '#7F7F7F',

    'code_font_size': '13px',
    'font_size': '15px',}


# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html', 'searchbox.html']``.

#html_sidebars = {'**': ['globaltoc.html','relations.html',  'searchbox.html']}
html_sidebars = {
    '**': [
        'about.html',
        #'navigation.html',
        'globaltoc.html',
        'searchbox.html',
        #'relations.html',
        #'donate.html',
    ]
}

html_show_copyright = False
html_show_sphinx = False
html_show_sourcelink = False

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Extension configuration -------------------------------------------------

#### Run notebook configuration
###
#### The template used when exporting from nbconvert
####   full  - Outputs the full HTML document [Default]
####   basic - Outputs a single div (with no additional resources)
###run_notebook_export_template = 'basic'  # Default: 'full'
###
#### Display the source links to the generated evaluated files
###run_notebook_display_source_links = False  # Default: True

